version: 2.1
jobs:
  install:
    parameters:
      python-version:
        type: string
    working_directory: ~/project
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - run:
          name: Set python << parameters.python-version >>
          command: |
            pyenv versions
            pyenv global << parameters.python-version >>
            python -m pip install --upgrade pip setuptools wheel
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - docker-<< parameters.python-version >>-{{ checksum "setup.py" }}-{{ checksum "dev_requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r dev_requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: docker-<< parameters.python-version >>-{{ checksum "setup.py" }}-{{ checksum "dev_requirements.txt" }}
  lint:
    working_directory: ~/project
    docker:
      - image: cimg/python:3.7.10
    steps:
      - run:
          name: Set python 3.7.10
          command: |
            pyenv global 3.7.10
            python -m pip install --upgrade pip setuptools wheel
      - checkout
      - restore_cache:
          key: docker-3.7.10-{{ checksum "setup.py" }}-{{ checksum "dev_requirements.txt" }}
      - run:
          name: run pylint
          command: |
            . venv/bin/activate
            make lint
      - store_artifacts:
          path: lint-project-reports
          destination: lint-project-reports
  test:
    parameters:
      python-version:
        type: string
    working_directory: ~/project
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - run:
          name: Set python << parameters.python-version >>
          command: |
            pyenv global << parameters.python-version >>
            python -m pip install --upgrade pip setuptools wheel
      - checkout
      - restore_cache:
          key: docker-<< parameters.python-version >>-{{ checksum "setup.py" }}-{{ checksum "dev_requirements.txt" }}
      - run:
          name: run pytest
          command: |
            . venv/bin/activate
            make test

workflows:
  main:
    jobs:
      - install:
          matrix:
            parameters:
              python-version: ["3.6.13", "3.7.10", "3.8.8", "3.9.11"]
      - lint:
          requires:
            - install
      - test:
          matrix:
            parameters:
              python-version: ["3.6.13", "3.7.10", "3.8.8", "3.9.11"]
          requires:
            - install
